//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms_prov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public Moneda()
        {
            this.products = new HashSet<product>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Simbolo { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
