//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms_prov
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.ImgProducts = new HashSet<ImgProduct>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> IdCategory { get; set; }
    
        public virtual ICollection<ImgProduct> ImgProducts { get; set; }

        
        public virtual Category Category { get; set; }
    }
}
